dist: xenial
language: node_js
node_js:
- 10.9.0
cache:
  directories:
  - node_modules
services:
- postgresql
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  - PGPORT=5433
before_script:
- ps aux | grep postgres
- psql -c 'create database travis_ci_test;' -U postgres
script:
- node server/setup.js
- npm test
