export const API_URL = process.env.REACT_APP_API_URL;
export const WS_URL = process.env.REACT_APP_SOCKET_URL;
export const TASKS_CHANGED = process.env.REACT_APP_TASKS_CHANGED;
export const TASK_CREATED = process.env.REACT_APP_TASK_CREATED;
export const TASK_COMPLETED = process.env.REACT_APP_TASK_COMPLETED;
export const TASK_CANCELLED = process.env.REACT_APP_TASK_CANCELLED;
export const TASK_ALL = process.env.REACT_APP_TASK_ALL;
export const SESSION_CHANGE = process.env.REACT_APP_SESSION_CHANGE;
export const TASK_TITLE = 'Task description\nDouble click to edit';
